### ISSUE TITLE
[BUG] Google Earth Pro doesn't uninstall

### ISSUE THREAD

**Issue by jamy015** [mikeee/ChocoPackages#7] opened 2020-09-05 13:09 UTC
**Describe the Issue**
I attempted to uninstall `googleearthpro v7.3.3` via Chocolatey, and it said the following:

```
googleearthpro v7.3.3
 Running auto uninstaller...
 Skipping auto uninstaller - 'Google Earth Pro' appears to have been uninstalled already by other means.
 googleearthpro has been successfully uninstalled.
```

However, looking at Settings > Apps showed that GEP was actually still installed.

**To Reproduce**
`choco uninstall googleearthpro`

**Expected behavior**
Chocolatey actually uninstalls GEP from the system.

**Device (please complete the following information):**
 - OS: Windows 10 Education
 - OS Update Version: 1909
 - Application: googleearthpro
 - Version: 7.3.3

**Comment by mikeee** [comment] 2020-09-07 00:27
I'm not able to reproduce this, could you perhaps try making sure that there are no issues with your initial installation?

`choco install googleearthpro --force` should do the trick and then try uninstalling again.

**Comment by mikeee** [comment] 2021-02-05 20:06
Let me know if you're still having issues, I'm closing this awaiting further input for now.

**Closed by mikeee** 2021-02-05 20:06 UTC
Labels: wontfix
